### ISSUE TITLE
what kind of view that i can connect with "@IBOutlet weak var circularPicker: AGCircularPicker!"

### ISSUE THREAD

**Issue by justin3527** [agilie/AGCircularPicker#2]
hello .
this source is very awesome
i shout when i found this library

but i have some problem when i use it
can you help me?

what kind of view that i can connect with "@IBOutlet weak var circularPicker: AGCircularPicker!"
i never know 
please help me
i need the this library 

thank you

**Comment by justin3527** [comment]
![2017-07-09 5 25 17](https://user-images.githubusercontent.com/23233979/27992285-af05d00c-64cb-11e7-8d44-801e324047f1.png)

And i have this issue
this code is sample code

**Comment by savilov** [comment]
Hi @justin3527, AGCircularPicker is a UIView, so you can add UIView in storyboard or xib and specify AGCircularPicker class in Identity Inspector. Another option is to add the AGCircularPicker from the code.

Regarding the crash can you please provide more information about it? Did you just download the example and run it? Or did you try to create your own example?

**Comment by justin3527** [comment]
hi @savilov , first of all , i really thank you for your kind comment
then i try again, but i still have some issue
1. l try that i link the IBOutlet variable and UIView in the storyboard 
but it is not connected 
![2017-07-11 11 31 39](https://user-images.githubusercontent.com/23233979/28048661-53867ea8-662d-11e7-9d03-1c2078eecc48.png)

2. i try that i add the variable of AGCircularPicker using addSubView method
but it also occur the clash when i add the options
this code is copied the your example to my class
![2017-07-11 11 33 14](https://user-images.githubusercontent.com/23233979/28048747-de18286e-662d-11e7-9335-b91d8db3533b.png)

can you help me again?
i really hope to using your library

thank you

**Comment by justin3527** [comment]
my test env is [iphone7 / swift3.0 / xcode8.3.3 / ios 10.3.2]

**Comment by savilov** [comment]
Hi @justin3527 

1. To connect IBOutlet you should specify the class for UIView in the Identity Inspector like this:
<img width="855" alt="circular_picker" src="https://user-images.githubusercontent.com/2720153/28055822-477380fc-6623-11e7-9798-bd357052f15b.png">

2. The reason why app crashes is that when you set options your circularPicker property is nil, so you need to initialize it before setting options. For instance:

`        circularPicker = AGCircularPicker(frame: CGRect(x: 0, y: 0, width: 300, height: 300))`
`        circularPicker.options = [hourOption, minuteOption, secondOption]`
`        circularPicker.delegate = self`

**Comment by justin3527** [comment]
oh, @savilov ! really thannnnnnnk yooooou!!!
I feel scarcity and shame.
this issue is very basic problem 
I once again feel my shortage.

I am currently in the learning step. so your teaching is very helpful
i could learn the new skill of iOS

Thank you once more
