### ISSUE TITLE
AGCircularPickerView move issue when i use the multi mode

### ISSUE THREAD

**Issue by justin3527** [agilie/AGCircularPicker#3]
when i move the view using swipe in the multi mode, it is move to the previous view
(when move using touch, it is normal)

is it AGCircularPicker issue ? or my mistake?
when you have some time, i hope that you check this issue
thank you very much 

ps. it is reproduce video
[AGCircularPicker_multi_move_issue.mov.zip](https://github.com/agilie/AGCircularPicker/files/1138331/AGCircularPicker_multi_move_issue.mov.zip)

**Comment by savilov** [comment]
Hi @justin3527, we've already released a new version (0.1.3) today with this fix
