### ISSUE TITLE
how can i get current value?

### ISSUE THREAD

**Issue by justin3527** [agilie/AGCircularPicker#4]
how can i get current value?
i can not found method

**Comment by savilov** [comment]
Hi @justin3527, currently all changes made by user is reported by `AGCircularPickerDelegate` or `AGCircularPickerViewDelegate` depending on what component is used.

It's good idea to add the possibility to obtain values at any time it's needed. We will add it soon. Thanks for reporting

**Comment by savilov** [comment]
Hi @justin3527, we've released 0.1.4 version and now you are able to get current values
