### ISSUE TITLE
Decimals?

### ISSUE THREAD

**Issue by alexjordaan** [agilie/AGCircularPicker#5]
Can this be used with Double rather than Int so that the value can contain decimals? I need 50.5 for example?

**Comment by savilov** [comment]
Hi @alexjordaan, currently, the library doesn't support decimal values, but you can make a simple workaround to have this functionality.
Let's say you need to pick values from 0 to 10 with step 0.5. So you can setup picker with range 0..20 and then just devide the result by 2. So when value is 20 it will be 10, 11 will be 5.5 etc.

**Comment by alexjordaan** [comment]
Clever. Thanks for the direction!
